Repository RiomaxGit/Avacado, pull requests merged in 2024-12, with the labels that each got.

#3 Development - creating login template
  avacado/chatlogic/templates/loginPage.html
Labels: development

#5 Development/setting websockets
  .gitignore
  avacado/chatlogic/consumer.py
  requirements.txt
Labels: development

#6 Development - adding static folder, add styles
  avacado/chatlogic/static/script.js
  avacado/chatlogic/static/style.css
Labels: development

#7 Documentation : How to run the project
  .gitignore
  avacado/avacado/__pycache__/__init__.cpython-310.pyc
  avacado/avacado/__pycache__/settings.cpython-310.pyc
  avacado/avacado/__pycache__/urls.cpython-310.pyc
  avacado/db.sqlite3
  readme.md
Labels: documentation

#8 settingup asgi.
  avacado/avacado/asgi.py
Labels: development

#11 adding asgi to settings.py
  avacado/avacado/settings.py
Labels: development

#10 Development - Setting up routing url for chatlogic
  avacado/avacado/urls.py
Labels: development

#12 adding frontend-script
  avacado/chatlogic/static/script.js
Labels: development

#13 Development - Initializing chatlogic and apps
  avacado/chatlogic/__init__.py
  avacado/chatlogic/admin.py
  avacado/chatlogic/apps.py
  avacado/chatlogic/models.py
  avacado/chatlogic/tests.py
Labels: development

#15 Updating Requirements
  requirements.txt
Labels: development

#17 unit testing the application
  avacado/chatlogic/tests.py
Labels: testing

#18 Adding cicd pipeline
  avacado/.github/workflows/ci.yml
Labels: development

#22 Bug Fix: Fixing the pipeline
  .github/workflows/ci.yml
Labels: bug, CI/CD

#24 Updating Test cases
  avacado/chatlogic/tests.py
  requirements.txt
Labels: bug, CI/CD

#25 Devops - Setting up dockerhub
  .github/workflows/ci.yml
Labels: CI/CD
